로비에서 leave했을 때 기능 구현
TeamTailHead/TailHeadServer pull request #1
Opened 2022-10-27 13:31 UTC by csb9427

2022-10-27 13:48 UTC, Tekiter requested changes

2022-10-27 13:48 UTC, Tekiter commented on src/Game.ts
> +
주석 없애주세요

2022-10-27 13:48 UTC, Tekiter commented on src/Game.ts
> +    }
```suggestion
    if (leavedPlayerId == this.adminPlayerId) {
      if (this.players.length > 0) {
        this.adminPlayerId = this.players[0].id;
      }
      else {
        this.adminPlayerId = null;
      }
    }
```

2022-10-29 13:02 UTC, csb9427 commented on src/Game.ts
> +    }
수정했습니다~~

2022-10-29 14:08 UTC, Tekiter requested changes
방장이 아닌 사람이 나가는 거에 대한 테스트도 추가해줘!

2022-10-29 14:08 UTC, Tekiter commented on src/Game.test.ts
> +  test("should leave", () => {
```suggestion
  test("should leave room admin", () => {
```

2022-10-29 15:53 UTC, csb9427 commented on src/Game.test.ts
> +  test("should leave", () => {
넵 수정했습니다

2022-10-30 00:39 UTC, Tekiter approved these changes
굳굳!!

2022-11-02 11:02 UTC, merged